version: '3.9'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: sam_website
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
